#!/usr/bin/env python3
"""Mirror brand assets from assets/ into site/static/.

The website (site/, Zola — see docs/research/mindfork-io-website.md) embeds
the generated screenshots, the wordmarks and the icon. Their single source of
truth is assets/ (screenshots are regenerated by the demo-screenshots
pipeline and rot-gated there), so the copies under site/static/ are derived
data: gitignored, recreated by this script before a local `zola serve` and by
the site CI before `zola build`.

Usage:
    python tools/site_sync_assets.py
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (source under assets/, destination under site/static/)
COPIES: list[tuple[str, str]] = [
    ("assets/mindfork.ico", "site/static/favicon.ico"),
    ("assets/mindfork-wordmark-dark.svg", "site/static/brand/mindfork-wordmark-dark.svg"),
    ("assets/mindfork-wordmark-light.svg", "site/static/brand/mindfork-wordmark-light.svg"),
    ("assets/mindfork-icon-transparent.svg", "site/static/brand/mindfork-icon-transparent.svg"),
    ("assets/mindfork-icon-256.png", "site/static/brand/mindfork-icon-256.png"),
    # The social preview card (tools/og_card.py) — 1200x630, what a link to
    # the site renders as anywhere social.
    ("assets/og-card.png", "site/static/brand/og-card.png"),
]


def main() -> int:
    pairs = list(COPIES)
    shots_dir = ROOT / "assets" / "screenshots"
    shots = sorted(shots_dir.glob("*.png")) + sorted(shots_dir.glob("*.svg"))
    if not shots:
        print("error: no renders under assets/screenshots/", file=sys.stderr)
        return 1
    pairs += [
        (f"assets/screenshots/{p.name}", f"site/static/screenshots/{p.name}")
        for p in shots
    ]
    for src_rel, dst_rel in pairs:
        src, dst = ROOT / src_rel, ROOT / dst_rel
        if not src.is_file():
            print(f"error: missing {src_rel}", file=sys.stderr)
            return 1
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
    print(f"synced {len(pairs)} files into site/static/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
